Added dtos for movie, movieSession,user and controllers for this entities
andriylagun/hibernate-online-cinema pull request #8
Opened 2020-10-22 07:40 UTC by andriylagun

2020-10-22 14:26 UTC, AnaLanda commented on src/main/java/com/online/cinema/dto/movie/MovieResponseDto.java
> +    private String title;
Maybe we'll need to have the `description` here as well

2020-10-22 14:28 UTC, AnaLanda commented on src/main/java/com/online/cinema/dto/moviesession/MovieSessionRequestDto.java
> +    private String sessionTime;
I think you can have a String that represents date+time here, like the `LocalDateTime` format `ISO_LOCAL_DATE_TIME` or something like it

2020-10-22 14:28 UTC, AnaLanda commented on src/main/java/com/online/cinema/dto/moviesession/MovieSessionResponseDto.java
> +    private String sessionTime;
Same here

2020-10-22 14:29 UTC, AnaLanda commented on src/main/java/com/online/cinema/dto/user/UserRegisterDto.java
> +public class UserRegisterDto {
```suggestion
public class UserRequestDto {
```

2020-10-22 14:30 UTC, AnaLanda reviewed
Looks great! 😃

2020-10-23 07:59 UTC, Sofasmile commented on src/main/java/com/online/cinema/controller/AuthenticationController.java
> +    private RedirectView register(@RequestBody UserRegisterDto userDto) {
зараз ми можемо зробити цей метод void, а в майбутньому повертати статус код що операція пройшла успішно

2020-10-23 07:59 UTC, Sofasmile commented on src/main/java/com/online/cinema/controller/MovieController.java
> +    public RedirectView addMovie(@RequestBody MovieRequestDto movieRequestDto) {
the same here

2020-10-23 07:59 UTC, Sofasmile commented on src/main/java/com/online/cinema/controller/MovieSessionController.java
> +        return new RedirectView("/avaliable");
and here

2020-10-23 07:59 UTC, Sofasmile commented on src/main/java/com/online/cinema/controller/MovieSessionController.java
> +    public List<MovieSessionResponseDto> getAllAvailableSessions(Long movieId, String date) {
let's change String to LocalDate

2020-10-23 07:59 UTC, Sofasmile commented on src/main/java/com/online/cinema/config/AppConfig.java
> +        "com.online.cinema.dto"
```suggestion
        "com.online.cinema.mapper or com.online.cinema.dto.mapper"
```

2020-10-23 07:59 UTC, Sofasmile commented on src/main/java/com/online/cinema/dto/moviesession/MovieSessionRequestDto.java
> +    private String sessionTime;
```suggestion
    private String sessionDateTime;
```

2020-10-23 07:59 UTC, Sofasmile commented on src/main/java/com/online/cinema/dto/moviesession/MovieSessionResponseDto.java
> +    private String sessionTime;
```suggestion
    private String sessionDateTime;
```

2020-10-23 13:54 UTC, Sofasmile commented on src/main/java/com/online/cinema/controller/MovieSessionController.java
> +    public List<MovieSessionResponseDto> getAllAvailableSessions(Long movieId, LocalDate date) {
does this method work correctly?

2020-10-27 12:38 UTC, KseniiaMakarova requested changes

2020-10-27 12:38 UTC, KseniiaMakarova commented on src/main/java/com/online/cinema/controller/MovieSessionController.java
> +            @RequestParam Long movieId, @RequestParam LocalDate date) {
please provide the screenshot if this works

2020-10-27 13:17 UTC, KseniiaMakarova approved these changes

2020-10-28 09:01 UTC, merged